source "https://supermarket.getchef.com"

cookbook "apt"
cookbook "git"
cookbook "java"
cookbook "chef-sbt"
cookbook "redis",        git: "https://github.com/miah/chef-redis.git"
cookbook "apache_kafka", path: "./site-cookbooks/apache_kafka"
cookbook "hosts_setup",  path: "./site-cookbooks/hosts_setup"
cookbook "redis_setup",  path: "./site-cookbooks/redis_setup"
